### PR TITLE
fix(scan): fix clocked and scheduled scan not working

### LINKED ISSUE #181: bug(scan): clocked scan and Periodic Scan are not working
### Current Behavior

I've configured both clocked and periodic scans for a target. Despite the scan run count indicating 1, no results are appearing in the results tab or anywhere else. Has anyone else encountered this issue? Any suggestions or solutions?

### Expected Behavior

Once the scheduled scan runs it should show the results in the "scan history".

### Steps To Reproduce

start a periodic/clocked scan

### Environment

```markdown
- reNgine: 2.1.0
- OS: Debian 12
- Python: 3.10
- Docker Engine: 
- Docker Compose: 
- Browser:
```

### Anything else?

_No response_

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

### PR DESCRIPTION
**Pull request by psyray**
Fixes #181 

Periodic and schedule scan are now working again.

There was also an UTC time problem.
So the timezone offset is gathered from the user browser and start datetime of the scan are send to beat in UTC if there's an interval

Tested and working

### CODE REVIEW

**Comment by 0b3ud** [comment]
I have tested the features mentioned above 

- Both periodic scan and scheduled scan seem to work for me 

- The scans always ran at the expected time 

Only 'one issue' I've noticed and that is the time shown is in UTC but maybe it is normal : 
image

**Comment by AnonymousWP** [comment]
> I have tested the features mentioned above
> 
> * Both periodic scan and scheduled scan seem to work for me
> * The scans always ran at the expected time
> 
> Only 'one issue' I've noticed and that is the time shown is in UTC but maybe it is normal : image

I think we should be able to fetch the system date/time from the system quite easily.

**Comment by psyray** [comment]
> > I have tested the features mentioned above
> > 
> > * Both periodic scan and scheduled scan seem to work for me
> > * The scans always ran at the expected time
> > 
> > Only 'one issue' I've noticed and that is the time shown is in UTC but maybe it is normal : image
> 
> I think we should be able to fetch the system date/time from the system quite easily.

I've already did this but it's not reliable as the UI could be in one timezones and the celery in another (for distributed configuration).
Do we must rely on the UTC time instead of the local time of the UI

**Comment by AnonymousWP** [comment]
> > > I have tested the features mentioned above
> > > 
> > > * Both periodic scan and scheduled scan seem to work for me
> > > * The scans always ran at the expected time
> > > 
> > > Only 'one issue' I've noticed and that is the time shown is in UTC but maybe it is normal : image
> > 
> > 
> > I think we should be able to fetch the system date/time from the system quite easily.
> 
> I've already did this but it's not reliable as the UI could be in one timezone and the celery in another (for distributed configuration). So we must rely on the UTC time instead of the local time of the UI

Hmm, maybe we should set the time on container level then. Also, if we're not going to implement it at all, then at least mention it's UTC, like so:

> 10:27pm (UTC)

**Comment by psyray** [comment]
> > > > I have tested the features mentioned above
> > > > 
> > > > * Both periodic scan and scheduled scan seem to work for me
> > > > * The scans always ran at the expected time
> > > > 
> > > > Only 'one issue' I've noticed and that is the time shown is in UTC but maybe it is normal : image
> > > 
> > > 
> > > I think we should be able to fetch the system date/time from the system quite easily.
> > 
> > 
> > I've already did this but it's not reliable as the UI could be in one timezone and the celery in another (for distributed configuration). So we must rely on the UTC time instead of the local time of the UI
> 
> Hmm, maybe we should set the time on container level then. 

Not possible we will have problem with Celery in the future, for sure.

> Also, if we're not going to implement it at all, then at least mention it's UTC, like so:
> 
> > 10:27pm (UTC)
> 
> Can just be hardcoded.

I will do that

**Comment by psyray** [comment]
Done
image

**Review by AnonymousWP — APPROVED** [review]
Approving & merging for now, although I can hardly imagine there's no way of doing this in a practical way. Perhaps in the future we'll come up with a solution.

**Pull request merged**
